<html>

<head>
    <?php $this->assets->outputcss('cssHeader'); ?>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>

<body>

<ul id="slide-out" class="side-nav">
    <li><div class="userView">
            <a href="#!name"><span class="white-text name">John Doe</span></a>
            <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
        </div></li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
</ul>
<a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>




<table>
    <tbody>
<?php



$layerHash = ['input', 'hidden', 'output'];


foreach($layerHash as $layerName) {
    echo "<tr><td>";
    echo "<a class='waves-effect waves-light btn'>$layerName</a>";
    echo "</td>";
    echo "<td>";

    /**
     * @var \ai\NeuralNetwork $neuralnetwork
     */
    foreach($neuralnetwork->getLayer($layerName) as $inputNeuron)
    {
        echo '<div class="chip">' . $inputNeuron . "</div>";
    }
    echo "</td></tr>";
}
?>
    </tbody>
</table>



<!-- Compiled and minified JavaScript -->



<?php $this->assets->outputJs('jsFooter'); ?>
</body>

</html>